import { cpSync, rmSync, mkdirSync, copyFileSync, writeFileSync } from 'fs';
import { execFileSync } from 'child_process';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const deployDir = join(root, 'dist', 'deploy');
const demoDir = join(root, 'dist', 'demo');
const readmeDir = join(root, 'dist', 'readme');

// Clean and recreate deploy folder
rmSync(deployDir, { recursive: true, force: true });
mkdirSync(deployDir, { recursive: true });

// Copy demo build to root of deploy/
cpSync(demoDir, deployDir, { recursive: true });

// Copy readme build to deploy/readme/
cpSync(readmeDir, join(deployDir, 'readme'), { recursive: true });

// Copy .htaccess into deploy root
copyFileSync(join(root, 'deploy', 'htaccess-soundmanager.txt'), join(deployDir, '.htaccess'));

// ---------------------------------------------------------------------------
// Sitemap
//
// public/sitemap.xml carries hand-typed lastmod dates, which go stale the
// moment anyone forgets to edit them, and a lastmod Google has learned to
// distrust is worth less than none at all. So the deployed copy is generated
// here instead, with each page's date taken from the last commit that touched
// its sources. Build timestamps would be wrong for the opposite reason: every
// deploy would claim every page changed.
//
// No git (a build from a tarball, say)? Then the copy vite already placed in
// dist/deploy/ stays, and nothing is lost.
// ---------------------------------------------------------------------------
const SITE = 'https://soundmanager.chriscreativecode.com';

// Shared sources: a change here really does change every page on the site.
const SHARED = ['src/demo/components', 'src/demo/shared.css', 'src/demo/services'];

const PAGES = [
  {
    url: '/',
    priority: '1.0',
    changefreq: 'weekly',
    sources: [
      'src/demo/pages/main/index.html',
      'src/demo/pages/main/landing.css',
      'src/demo/pages/main/main.ts',
      ...SHARED,
    ],
  },
  { url: '/readme/', priority: '0.8', changefreq: 'weekly', sources: ['README.md', 'src/readme'] },
  { url: '/general/', priority: '0.6', changefreq: 'monthly', sources: ['src/demo/pages/main/general', ...SHARED] },
  { url: '/multichannel/', priority: '0.6', changefreq: 'monthly', sources: ['src/demo/pages/main/multichannel', ...SHARED] },
  { url: '/spatial/', priority: '0.6', changefreq: 'monthly', sources: ['src/demo/pages/main/spatial', ...SHARED] },
  { url: '/groups/', priority: '0.6', changefreq: 'monthly', sources: ['src/demo/pages/main/groups', ...SHARED] },
  { url: '/sprite/', priority: '0.6', changefreq: 'monthly', sources: ['src/demo/pages/main/sprite', ...SHARED] },
];

function lastCommitDate(sources) {
  // %cs is the committer date as YYYY-MM-DD, which is exactly the W3C date
  // format sitemaps accept.
  const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', ...sources], {
    cwd: root,
    encoding: 'utf8',
  }).trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(out)) throw new Error(`unexpected git date: "${out}"`);
  return out;
}

try {
  const entries = PAGES.map((page) => {
    const lastmod = lastCommitDate(page.sources);
    return [
      '  <url>',
      `    <loc>${SITE}${page.url}</loc>`,
      `    <lastmod>${lastmod}</lastmod>`,
      `    <priority>${page.priority}</priority>`,
      `    <changefreq>${page.changefreq}</changefreq>`,
      '  </url>',
    ].join('\n');
  });

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/prepare-deploy.js. Do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    '</urlset>',
    '',
  ].join('\n');

  writeFileSync(join(deployDir, 'sitemap.xml'), xml);
  console.log('Sitemap generated with lastmod from git history.');
} catch (error) {
  console.warn(`Sitemap not generated (${error.message}); keeping public/sitemap.xml as shipped.`);
}

console.log('Deploy folder prepared:');
console.log('  dist/demo/   → dist/deploy/         (upload to public_html/)');
console.log('  dist/readme/ → dist/deploy/readme/  (upload to public_html/readme/)');
console.log('  deploy/htaccess-soundmanager.txt → dist/deploy/.htaccess');
