export enum SoundEventsEnum {
    ENDED = 'ended',
    ERROR = 'error',
    FADE_IN_COMPLETED = 'fade_in_completed',
    FADE_OUT_COMPLETED = 'fade_out_completed',
    FADE_MASTER_IN_COMPLETED = 'fade_master_in_completed',
    FADE_MASTER_OUT_COMPLETED = 'fade_master_out_completed',
    MASTER_VOLUME_CHANGED = 'master_volume_changed',
    MUTED = 'muted',
    MUTE_GLOBAL = 'mute_global',
    UNMUTE_GLOBAL = 'unmute_global',
    MASTER_PAN_CHANGED = 'master_pan_changed',
    PAUSED = 'paused',
    RESUMED = 'resumed',
    SEEKED = 'seeked',
    STARTED = 'started',
    STOPPED = 'stopped',
    UNMUTED = 'unmuted',
    VOLUME_CHANGED = 'volume_changed',
  }