export enum SoundEventsEnum {
    ENDED = 'ended',
    ERROR = 'error',
    FADE_IN_COMPLETED = 'fade_in_completed',
    FADE_OUT_COMPLETED = 'fade_out_completed',
    FADE_MASTER_IN_COMPLETED = 'fade_master_in_completed',
    FADE_MASTER_OUT_COMPLETED = 'fade_master_out_completed',
    GLOBAL_SPATIAL_POSITION_CHANGED = 'global_spatial_position_changed',
    LOOP_COMPLETED = 'loop_completed',
    MASTER_VOLUME_CHANGED = 'master_volume_changed',
    MUTED = 'muted',
    MUTE_GLOBAL = 'mute_global',
    UNMUTE_GLOBAL = 'unmute_global',
    MASTER_PAN_CHANGED = 'master_pan_changed',
    OPTIONS_UPDATED = 'options_updated',
    PAN_CHANGED = 'pan_changed',
    PAUSED = 'paused',
    RESET = 'reset',
    RESUMED = 'resumed',
    SEEKED = 'seeked',
    SPATIAL_POSITION_CHANGED = 'spatial_position_changed',
    SPATIAL_POSITION_RESET = 'spatial_position_reset',
    STARTED = 'started',
    STOPPED = 'stopped',
    UPDATED_URL = 'updated_url',
    UNMUTED = 'unmuted',
    VOLUME_CHANGED = 'volume_changed',
  }